export const DEFAULT_CATEGORIES = [
  {
    id: 'food',
    name: 'Food & Dining',
    icon: '🍔',
    color: '#FF6B6B',
    subcategories: [
      { id: 'food_groceries', name: 'Groceries' },
      { id: 'food_restaurant', name: 'Restaurant' },
      { id: 'food_cafe', name: 'Cafe & Coffee' },
      { id: 'food_delivery', name: 'Food Delivery' },
      { id: 'food_snacks', name: 'Snacks' },
    ],
  },
  {
    id: 'transport',
    name: 'Transportation',
    icon: '🚗',
    color: '#4ECDC4',
    subcategories: [
      { id: 'transport_fuel', name: 'Fuel' },
      { id: 'transport_public', name: 'Public Transit' },
      { id: 'transport_taxi', name: 'Taxi & Ride Share' },
      { id: 'transport_parking', name: 'Parking' },
      { id: 'transport_maintenance', name: 'Vehicle Maintenance' },
    ],
  },
  {
    id: 'shopping',
    name: 'Shopping',
    icon: '🛍️',
    color: '#45B7D1',
    subcategories: [
      { id: 'shopping_clothes', name: 'Clothing' },
      { id: 'shopping_electronics', name: 'Electronics' },
      { id: 'shopping_home', name: 'Home & Garden' },
      { id: 'shopping_personal', name: 'Personal Care' },
      { id: 'shopping_gifts', name: 'Gifts' },
    ],
  },
  {
    id: 'bills',
    name: 'Bills & Utilities',
    icon: '📄',
    color: '#96CEB4',
    subcategories: [
      { id: 'bills_electricity', name: 'Electricity' },
      { id: 'bills_water', name: 'Water' },
      { id: 'bills_internet', name: 'Internet & Phone' },
      { id: 'bills_rent', name: 'Rent' },
      { id: 'bills_insurance', name: 'Insurance' },
    ],
  },
  {
    id: 'health',
    name: 'Health & Fitness',
    icon: '🏥',
    color: '#FFEAA7',
    subcategories: [
      { id: 'health_medical', name: 'Medical' },
      { id: 'health_pharmacy', name: 'Pharmacy' },
      { id: 'health_gym', name: 'Gym & Sports' },
      { id: 'health_wellness', name: 'Wellness' },
    ],
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    icon: '🎬',
    color: '#DDA0DD',
    subcategories: [
      { id: 'ent_movies', name: 'Movies & Shows' },
      { id: 'ent_games', name: 'Games' },
      { id: 'ent_subscriptions', name: 'Subscriptions' },
      { id: 'ent_hobbies', name: 'Hobbies' },
      { id: 'ent_events', name: 'Events & Concerts' },
    ],
  },
  {
    id: 'travel',
    name: 'Travel',
    icon: '✈️',
    color: '#74B9FF',
    subcategories: [
      { id: 'travel_flights', name: 'Flights' },
      { id: 'travel_hotel', name: 'Hotels & Stays' },
      { id: 'travel_activities', name: 'Activities' },
      { id: 'travel_food', name: 'Travel Food' },
    ],
  },
  {
    id: 'education',
    name: 'Education',
    icon: '📚',
    color: '#A29BFE',
    subcategories: [
      { id: 'edu_courses', name: 'Courses' },
      { id: 'edu_books', name: 'Books & Materials' },
      { id: 'edu_tuition', name: 'Tuition' },
    ],
  },
  {
    id: 'personal',
    name: 'Personal',
    icon: '👤',
    color: '#FD79A8',
    subcategories: [
      { id: 'personal_grooming', name: 'Grooming' },
      { id: 'personal_laundry', name: 'Laundry' },
      { id: 'personal_other', name: 'Other' },
    ],
  },
  {
    id: 'other',
    name: 'Other',
    icon: '📦',
    color: '#B2BEC3',
    subcategories: [
      { id: 'other_misc', name: 'Miscellaneous' },
      { id: 'other_fees', name: 'Bank Fees & Charges' },
      { id: 'other_donations', name: 'Donations' },
    ],
  },
];

export const INCOME_CATEGORIES = [
  { id: 'income_salary', name: 'Salary', icon: '🪙', color: '#00B894' },
  { id: 'income_freelance', name: 'Freelance', icon: '💻', color: '#00CEC9' },
  { id: 'income_business', name: 'Business', icon: '🏢', color: '#0984E3' },
  { id: 'income_investment', name: 'Investment', icon: '📈', color: '#6C5CE7' },
  { id: 'income_rental', name: 'Rental', icon: '🏠', color: '#E17055' },
  { id: 'income_gift', name: 'Gift', icon: '🎁', color: '#FDCB6E' },
  { id: 'income_refund', name: 'Refund', icon: '↩️', color: '#81ECEC' },
  { id: 'income_split_settlement', name: 'Split Settlement', icon: '🤝', color: '#55EFC4' },
  { id: 'income_other', name: 'Other', icon: '📦', color: '#B2BEC3' },
];
